apiVersion: v1
kind: Pod
metadata:
  name: volume-share-nautilus
spec:
  containers:
  - name: volume-container-nautilus-1
    image: fedora:latest
    command: ["sleep", "infinity"]
    volumeMounts:
    - mountPath: /tmp/news
      name: volume-share
  - name: volume-container-nautilus-2
    image: fedora:latest
    command: ["sleep", "infinity"]
    volumeMounts:
    - mountPath: /tmp/apps
      name: volume-share
  volumes:
  - name: volume-share
    emptyDir: {}