apiVersion: v1
kind: secret
metadata:
  name: media
type: Opaque
Files:
  
---
apiVersion: v1
kind: Pod
metadata: 
  name: secret-nautilus
spec:
  containers:
    - name: secret-container-nautilus
      image: fedora:latest
      command: ['sleep' , 'infinity']
      volumeMounts:
        - name: secret-volume-nautilus
          mountPath: /opt/cluster
          readOnly: true
  volumes:
    - name: secret-volume-nautilus
      secret:
        secretName: media # created secret file name as media
