apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"python-deployment-datacenter","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"python_app"}},"template":{"metadata":{"labels":{"app":"python_app"}},"spec":{"containers":[{"image":"poroko/flask-app-demo","name":"python-container-datacenter","ports":[{"containerPort":5000}]}]}}}}
  creationTimestamp: "2025-10-26T12:47:44Z"
  generation: 1
  name: python-deployment-datacenter
  namespace: default
  resourceVersion: "803"
  uid: 1ab099ef-f52b-4a4a-870f-36dfc835ef6e
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: python_app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python_app
    spec:
      containers:
      - image: poroko/flask-app-demo #this should be poroko/flask-demo-app
        imagePullPolicy: Always
        name: python-container-datacenter
        ports:
        - containerPort: 5000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2025-10-26T12:47:44Z"
    lastUpdateTime: "2025-10-26T12:47:44Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2025-10-26T12:47:44Z"
    lastUpdateTime: "2025-10-26T12:47:44Z"
    message: ReplicaSet "python-deployment-datacenter-6fdb496d59" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"python-service-datacenter","namespace":"default"},"spec":{"ports":[{"nodePort":32345,"port":8080}],"selector":{"app":"python_app"},"type":"NodePort"}}
  creationTimestamp: "2025-10-26T12:47:44Z"
  name: python-service-datacenter
  namespace: default
  resourceVersion: "793"
  uid: 5a338e41-0a8a-4474-a429-01b22951d472
spec:
  clusterIP: 10.96.252.141
  clusterIPs:
  - 10.96.252.141
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32345
    port: 8080 #this should be 5000
    protocol: TCP
    targetPort: 8080 #this should be 5000
  selector:
    app: python_app
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}