- name: Manage lines in files using Ansible Lineinfile Module
  hosts: all
  become: yes
  tasks:
    - name: install httpd package 
      ansible.builtin.yum:
        name: httpd
        state: present
    - name: start httpd service status
      ansible.builtin.systemd:
        name: httpd
        state: started
        enabled: yes
    - name: httpd status check  
      ansible.builtin.shell: "systemctl is-active httpd"

    - name: Create a file /var/www/html/index.html
      ansible.builtin.copy:
        dest: /var/www/html/index.html
        
        content: |
          "This is a Nautilus sample file, created using Ansible!"

    - name: Using lineinfile Ansible module add some more content
      ansible.builtin.lineinfile:
        path: /var/www/html/index.html
        line: "Welcome to xFusionCorp Industries!"
        insertbefore: BOF
        state: present
        owner: apache
        group: apache
        mode: '0755'

